# Generated by Django 4.2.13 on 2024-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('subtitle', models.TextField(max_length=500)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=100)),
                ('journalist', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.TextField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='publishedDate',
            new_name='published_date',
        ),
    ]
