# Generated by Django 4.2.12 on 2024-06-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='description',
        ),
    ]
