# Generated by Django 4.2.12 on 2024-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_descriptions_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdbUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
